### ISSUE TITLE
Displays static data (from the database) in sidebar.

### ISSUE THREAD

**Issue by bykandrey** [alexgarrett/simple-mvc#12]
Hi, Alex!

Thank you very much for all that you do and sorry for my English.

Tell me, please, how can I display a list of the all categories from the database in the left or right sidebar that would be shown on every page, so I going to another page also saw the list of categories?

Now to display a list of the all categories, I need to contact the appropriate controller and model and get all the data about categories.

Thank you very much.

**Comment by alexgarrett** [comment]
Hello! Could you email me?

The GH issues are for codebase issues :)
