### ISSUE TITLE
Fatal error: Class 'Whoops\Run' not found

### ISSUE THREAD

**Issue by vrsotto** [alexgarrett/simple-mvc#15]
Hello,

I'm on windows devlopment environment... when i try to run this app, i'm receiving this error: 

Fatal error: Class 'Whoops\Run' not found in X:\XAMPP\htdocs\devel\smvc\app\core\App.php on line 78

In (the only file i changed) start.php i uncommented:
require_once INC_ROOT . '/app/core/App.php';
require_once INC_ROOT . '/app/core/Controller.php';

and nothing else changed from the original repo.

Please help... 

thanks

**Comment by vrsotto** [comment]
Oh, I got it now. sorry! :D

**Comment by Viistorrr** [comment]
how did you fix it? Im having the same issue now.
